list: $/mavitm/subscription/models/subtype/columns.yaml
modelClass: Mavitm\Subscription\Models\Subtype
title: Subtypes
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'mavitm/subscription/subtypes/update/:id'
